#!/usr/bin/env node
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  ConstraintLayoutEngine,
  DeckEditor,
  PptxExporter,
  PresentationPipeline,
  TemplateLibrary,
  createStructuredOutputModel,
  loadLlmConfig,
} from './index.js';

const [, , topic = 'AI Presentation Generator', ...rest] = process.argv;
const sourceText = rest.join(' ').trim();
const cwd = process.cwd();
const outputPath = path.join(cwd, 'generated-deck.pptx');
const llmConfig = loadLlmConfig();

const pipeline = new PresentationPipeline({
  model: createStructuredOutputModel(),
  templates: new TemplateLibrary(),
  layoutEngine: new ConstraintLayoutEngine(),
  exporter: new PptxExporter(),
  editor: new DeckEditor(),
});

const result = await pipeline.buildAndExport({
  topic,
  audience: 'Product and engineering stakeholders',
  goal: 'Align on the recommended roadmap',
  sourceText,
}, outputPath);

const currentFile = fileURLToPath(import.meta.url);
console.log(`Presentation generated by ${path.basename(currentFile)} with ${llmConfig.provider}: ${outputPath}`);
console.log(`Outline sections: ${result.outline.sections.length}; slides: ${result.structuredDeck.slides.length}`);
